### ISSUE TITLE
Crash on run_finetuning.py 

### ISSUE THREAD

**Issue by Muertoe** [jumon/whisper-finetuning#14]
Hello. Thanks for creating this project. 

I created the training and validation data using your create_data.py script on several hundred tv shows with subtitles, but when I start run_finetuning.py it crashes here. 

Is there a workaround/fix for this? Thanks.

```
(pytorch) $ python run_finetuning.py --train-json train.json --dev-json validate.json --model large-v2
  0%|                                                                        | 0/125 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/me/whisper-finetuning/run_finetuning.py", line 294, in <module>
    main()
  File "/home/me/whisper-finetuning/run_finetuning.py", line 283, in main
    main_loop(
  File "/home/me/whisper-finetuning/run_finetuning.py", line 206, in main_loop
    min_loss = evaluate(model, dev_loader)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/me/whisper-finetuning/run_finetuning.py", line 165, in evaluate
    for x, y_in, y_out in tqdm(dev_loader):
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/me/whisper-finetuning/dataloader.py", line 146, in __getitem__
    special_tokens = self._get_special_tokens(is_text_empty, record.language, no_timestamps)
  File "/home/me/whisper-finetuning/dataloader.py", line 63, in _get_special_tokens
    self._get_single_token_id(f"<|{language}|>"),
  File "/home/me/whisper-finetuning/dataloader.py", line 50, in _get_single_token_id
    tokens = self.tokenizer.encode(text)
  File "/home/me/.local/lib/python3.10/site-packages/whisper/tokenizer.py", line 160, in encode
    return self.encoding.encode(text, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/tiktoken/core.py", line 112, in encode
    raise_disallowed_special_token(match.group())
  File "/home/me/.local/lib/python3.10/site-packages/tiktoken/core.py", line 322, in raise_disallowed_special_token
    raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|en|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|en|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|en|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.
```

**Comment by Ifan24** [comment]
You could try modifying lines 63 and 64 of the `dataloader.py` script as follows:

```python
# Change these lines:
                self._get_single_token_id(f"<|{language}|>"),
                self._get_single_token_id("<|transcribe|>"),
# To these:
                self.tokenizer.special_tokens[f"<|{language}|>"],
                self.tokenizer.special_tokens["<|transcribe|>"],
```

**Comment by emcodem** [comment]
@Ifan24  thanks, your suggestion worked for me! Without this, i would not have been able to run the scripts and it would have taken a very long time for me to get to a similar working solution.

**Comment by Muertoe** [comment]
> You could try modifying lines 63 and 64 of the `dataloader.py` script as follows:
> 
> ```python
> # Change these lines:
>                 self._get_single_token_id(f"<|{language}|>"),
>                 self._get_single_token_id("<|transcribe|>"),
> # To these:
>                 self.tokenizer.special_tokens[f"<|{language}|>"],
>                 self.tokenizer.special_tokens["<|transcribe|>"],
> ```

Thank you. That worked.

**Comment by jumon** [comment]
Thanks everyone for reporting the issue and suggesting the solution. The issue was due to the recent change I merged into the main branch. Therefore, I have reverted the commit related to that change, and everything should be functioning properly now. Thanks again!
